### ISSUE TITLE
ECP - Revisão e refinamento dos itens entregues na Sprint 1

### ISSUE THREAD

**Issue by felipesampaiosilva** [2023M6T1-Inteli/grupo5#38]
Revisão e refinamento dos itens entregues na Sprint 1 (contexto do problema a ser resolvido, dados disponíveis, objetivo do problema,recursos que representam limitações neste problema, expressões matemáticas que representam a função objetivo e as restrições/limitações do problema)

**Comment by Luiz-Granville** [comment]
Granville(Entendimento de negócio, Oceano azul e VPC)
